@extends('page-layout.master')
@section('section')
    @include('pages.nga-min.section1')
    @include('pages.nga-min.sec1')
    @include('pages.nga-min.sec2')
    @include('pages.nga-min.sec3')
    @include('pages.nga-min.sec4-vinh')
    @include('pages.home-page.sec4')
{{--    @include('pages.home-page.sec2')--}}
    @include('pages.nga-min.section5')
    @include('pages.nga-min.sec5-vinh')
    @include('pages.nga-min.sec6')
    @include('pages.nga-min.sec7-c')
    @include('pages.nga-min.sec8-c')
    @include('pages.nga-min.sec9')
    @include('pages.navigation-sec.navigation-sec')
@stop
