@extends('page-layout.master')
@section('section')
    @include('pages.home-page.section1')
    @include('pages.home-page.sec2')
    @include('pages.home-page.sec3')
    @include('pages.home-page.sec4-production')
    @include('pages.home-page.section5')
{{--    @include('pages.home-page.sec6')--}}
    @include('pages.home-page.section7')
    @include('pages.home-page.section8')
    @include('pages.home-page.sec8')
    @include('pages.home-page.section9')
    @include('pages.home-page.sec10')
    @include('pages.navigation-sec.navigation-sec')
@stop
